# Count languages by type

PREFIX lang:  <http://purl.obolibrary.org/obo/LANG_>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT (count(distinct ?lang) as ?nlang) ?type
WHERE {
    ?lang rdfs:subClassOf lang:0000001 . # is a language
    ?lang lang:0000007 ?type .  # capture the language type
}
GROUP BY ?type
ORDER BY ?type